version: '3.7'

services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:imenadel@flask_db:5432/pme
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=imenadel
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pme
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}